/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v12.0
processor: MKE16F256xxx16
package_id: MKE16F256VLH16
mcu_data: ksdk2_0
processor_version: 12.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '6', peripheral: CAN0, signal: RX, pin_signal: PTE4/BUSOUT/FTM2_QD_PHB/FTM2_CH2/CAN0_RX/FXIO_D6/EWM_OUT_b}
  - {pin_num: '5', peripheral: CAN0, signal: TX, pin_signal: PTE5/TCLK2/FTM2_QD_PHA/FTM2_CH3/CAN0_TX/FXIO_D7/EWM_IN}
  - {pin_num: '31', peripheral: LPSPI0, signal: SIN, pin_signal: ADC0_SE7/PTB3/FTM1_CH1/LPSPI0_SIN/FTM1_QD_PHA/TRGMUX_IN2}
  - {pin_num: '32', peripheral: LPSPI0, signal: SCK, pin_signal: ADC0_SE6/PTB2/FTM1_CH0/LPSPI0_SCK/FTM1_QD_PHB/TRGMUX_IN3}
  - {pin_num: '33', peripheral: LPSPI0, signal: SOUT, pin_signal: ADC0_SE5/ADC1_SE15/PTB1/LPUART0_TX/LPSPI0_SOUT/TCLK0}
  - {pin_num: '34', peripheral: LPSPI0, signal: PCS0, pin_signal: ADC0_SE4/ADC1_SE14/PTB0/LPUART0_RX/LPSPI0_PCS0/LPTMR0_ALT3/PWT_IN3}
  - {pin_num: '11', peripheral: SCG, signal: EXTAL0, pin_signal: EXTAL/PTB7/LPI2C0_SCL}
  - {pin_num: '12', peripheral: SCG, signal: XTAL0, pin_signal: XTAL/PTB6/LPI2C0_SDA}
  - {pin_num: '64', peripheral: CoreDebug, signal: SWD_DIO, pin_signal: PTA4/ACMP0_OUT/EWM_OUT_b/JTAG_TMS/SWD_DIO}
  - {pin_num: '62', peripheral: CoreDebug, signal: SWD_CLK, pin_signal: ACMP0_IN2/PTC4/FTM1_CH0/RTC_CLKOUT/EWM_IN/FTM1_QD_PHB/JTAG_TCLK/SWD_CLK}
  - {pin_num: '58', peripheral: CoreDebug, signal: TRACE_SWO, pin_signal: PTA10/FTM1_CH4/LPUART0_TX/FXIO_D0/JTAG_TDO/noetm_Trace_SWO}
  - {pin_num: '63', peripheral: RCM, signal: RESET, pin_signal: PTA5/TCLK1/JTAG_TRST_b/RESET_b}
  - {pin_num: '30', peripheral: GPIOC, signal: 'GPIO, 14', pin_signal: ADC0_SE12/ACMP2_IN5/PTC14/FTM1_CH2}
  - {pin_num: '35', peripheral: GPIOC, signal: 'GPIO, 9', pin_signal: ADC2_SE15/PTC9/LPUART1_TX/FTM1_FLT1/LPUART0_RTS}
  - {pin_num: '1', peripheral: LPSPI1, signal: SIN, pin_signal: ADC2_SE1/PTD1/FTM0_CH3/LPSPI1_SIN/FTM2_CH1/FXIO_D1/TRGMUX_OUT2}
  - {pin_num: '2', peripheral: LPSPI1, signal: SCK, pin_signal: ADC2_SE0/PTD0/FTM0_CH2/LPSPI1_SCK/FTM2_CH0/FXIO_D0/TRGMUX_OUT1}
  - {pin_num: '46', peripheral: LPSPI1, signal: SOUT, pin_signal: ADC1_SE2/PTD2/FTM3_CH4/LPSPI1_SOUT/FXIO_D4/TRGMUX_IN5}
  - {pin_num: '45', peripheral: LPSPI1, signal: PCS0, pin_signal: ADC1_SE3/PTD3/FTM3_CH5/LPSPI1_PCS0/FXIO_D5/TRGMUX_IN4/NMI_b}
  - {pin_num: '48', peripheral: LPUART0, signal: RX, pin_signal: ADC1_SE0/PTA2/FTM3_CH0/LPI2C0_SDA/EWM_OUT_b/LPUART0_RX}
  - {pin_num: '47', peripheral: LPUART0, signal: TX, pin_signal: ADC1_SE1/PTA3/FTM3_CH1/LPI2C0_SCL/EWM_IN/LPUART0_TX}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    /* PORTA10 (pin 58) is configured as noetm_Trace_SWO */
    PORT_SetPinMux(PORTA, 10U, kPORT_MuxAlt7);

    /* PORTA2 (pin 48) is configured as LPUART0_RX */
    PORT_SetPinMux(PORTA, 2U, kPORT_MuxAlt6);

    /* PORTA3 (pin 47) is configured as LPUART0_TX */
    PORT_SetPinMux(PORTA, 3U, kPORT_MuxAlt6);

    /* PORTA4 (pin 64) is configured as SWD_DIO */
    PORT_SetPinMux(PORTA, 4U, kPORT_MuxAlt7);

    /* PORTA5 (pin 63) is configured as RESET_b */
    PORT_SetPinMux(PORTA, 5U, kPORT_MuxAlt7);

    /* PORTB0 (pin 34) is configured as LPSPI0_PCS0 */
    PORT_SetPinMux(PORTB, 0U, kPORT_MuxAlt3);

    /* PORTB1 (pin 33) is configured as LPSPI0_SOUT */
    PORT_SetPinMux(PORTB, 1U, kPORT_MuxAlt3);

    /* PORTB2 (pin 32) is configured as LPSPI0_SCK */
    PORT_SetPinMux(PORTB, 2U, kPORT_MuxAlt3);

    /* PORTB3 (pin 31) is configured as LPSPI0_SIN */
    PORT_SetPinMux(PORTB, 3U, kPORT_MuxAlt3);

    /* PORTB6 (pin 12) is configured as XTAL */
    PORT_SetPinMux(PORTB, 6U, kPORT_PinDisabledOrAnalog);

    /* PORTB7 (pin 11) is configured as EXTAL */
    PORT_SetPinMux(PORTB, 7U, kPORT_PinDisabledOrAnalog);

    /* PORTC14 (pin 30) is configured as PTC14 */
    PORT_SetPinMux(PORTC, 14U, kPORT_MuxAsGpio);

    /* PORTC4 (pin 62) is configured as SWD_CLK */
    PORT_SetPinMux(PORTC, 4U, kPORT_MuxAlt7);

    /* PORTC9 (pin 35) is configured as PTC9 */
    PORT_SetPinMux(PORTC, 9U, kPORT_MuxAsGpio);

    /* PORTD0 (pin 2) is configured as LPSPI1_SCK */
    PORT_SetPinMux(PORTD, 0U, kPORT_MuxAlt3);

    /* PORTD1 (pin 1) is configured as LPSPI1_SIN */
    PORT_SetPinMux(PORTD, 1U, kPORT_MuxAlt3);

    /* PORTD2 (pin 46) is configured as LPSPI1_SOUT */
    PORT_SetPinMux(PORTD, 2U, kPORT_MuxAlt3);

    /* PORTD3 (pin 45) is configured as LPSPI1_PCS0 */
    PORT_SetPinMux(PORTD, 3U, kPORT_MuxAlt3);

    /* PORTE4 (pin 6) is configured as CAN0_RX */
    PORT_SetPinMux(PORTE, 4U, kPORT_MuxAlt5);

    /* PORTE5 (pin 5) is configured as CAN0_TX */
    PORT_SetPinMux(PORTE, 5U, kPORT_MuxAlt5);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
